#!/bin/bash

Green="\033[0;32m"
White="\033[1;37m"
Space="\t\t\t\t\t\t\t"
Format=${Space}${Green}

cat testData |
while read stuffToDo
do
        echo -e "${stuffToDo}${Format}[OK]${White}"
	sleep 0.5
done

git status
echo "Adding changes to log"
git status | grep "modified" > changes.log
grep -r "#ToDo" . > todo.log
find . -name "*.hs" | xargs ghc -fno-code > error.log
