	#include <p16F690.inc>
	__config (_INTRC_OSC_NOCLKOUT&_WDT_OFF&_PWRTE_OFF&_MCLRE_OFF&_CP_OFF&_BOR_OFF&_IESO_OFF&_FCMEN_OFF)

	cblock 0x20
	DELAY
	endc
	
	org 0
START
	BANKSEL ADCON0
	BCF ADCON0,0
	BANKSEL ANSEL
	bcf ANSEL,0
	BANKSEL ANSELH
	BCF ANSELH,0
	BANKSEL TRISC
	BCF TRISC,1
	BANKSEL PORTC
	BSF PORTC,1
	end