	#include <p16F690.inc>
	__config (_INTRC_OSC_NOCLKOUT&_WDT_OFF&_PWRTE_OFF&_MCLRE_OFF&_CP_OFF&_BOR_OFF&_IESO_OFF&_FCMEN_OFF)

	cblock 0x20
	DISPLAY
	DELAY1
	DELAY2
	endc
	
	org 0
START
	BANKSEL ADCON0
	BCF ADCON0,0
	BANKSEL ANSEL
	bcf ANSEL,0
	BANKSEL ANSELH
	BCF ANSELH,0
	BANKSEL TRISC
	CLRF TRISC
	BCF STATUS,RP0
	MOVLW 0X08
	MOVWF DISPLAY

MAIN
	MOVF DISPLAY,W
	MOVWF PORTC
	end
DELAY
	DECFSZ DELAY1
	GOTO DELAY
	DECFSZ DELAY2
	GOTO DELAY

	BCF STATUS,C
	RRF DISPLAY,F
	BTFSC STATUS,C
	BSF DISPLAY,3
	GOTO MAIN